config/routes.rb
Rails.application.routes.draw do
  scope module: :users do
    resources :reservations
    resource :user, only: [:edit, :show, :update] do
      resource :timetable, only: [:edit]
      resources :timetables, only: [:create, :destroy]
      
    end
    resources :bands
  end
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, path: "", controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  root to: 'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/band.rb
class Band < ApplicationRecord
  has_many :band_members
  has_many :users, through: :band_members
  has_many :reservations
  accepts_nested_attributes_for :band_members
  
  validates :name, presence: true
  
  def member_included?(member)
    f = false
    self.users.each do |user|
      if user.id == member.id
        f = true
      end
    end
    return f
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :timetables
  has_many :band_members
  has_many :bands, through: :band_members
end

app/controllers/users/bands_controller.rb
class Users::BandsController < ApplicationController
  def show
    @band = Band.find(params[:id])
  end

  def edit
    @band = Band.find(params[:id])
    @users = @users = User.where.not(id: current_user.id)
  end
  
  def update
    band = Band.find(params[:id])
    band.update(band_params)
    redirect_to bands_path
  end

  def index
    @bands = Band.all
  end

  def new
    @band = Band.new
    6.times {@band.band_members.build}
    @users = User.where.not(id: current_user.id)
  end
  
  def create
    band = Band.new(band_params)
    band.band_members = band.band_members.reject {|band_member| !band_member.user_id}
    band.band_members.build(user_id: current_user.id)
    if band.save
      redirect_to bands_path
    else
      redirect_to new_band_path
    end
  end
  
  def destroy
    band = Band.find(params[:id])
    band.delete
    redirect_to bands_path
  end
  
  private
  def band_params
    params.require(:band).permit(:name, band_members_attributes: [:user_id])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  skip_before_action :user_logged_in?, only: [:new, :create]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/reservations_controller.rb
class Users::ReservationsController < ApplicationController
  def index
    @reservations = Reservation.all
    @today = Date.today
    @repete_counts = 21
    if params[:page]
      @page = params[:page].to_i
    else
      @page = 0
    end
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def new
    @reservation = Reservation.new
    @reservation.date = params[:date]
    @reservation.period = params[:period]
    @bands = Band.joins(:band_members).where(band_members: {user_id: current_user.id})
  end
  
  def create
    @reservation = Reservation.new(reservation_params)
    @bands = Band.joins(:band_members).where(band_members: {user_id: current_user.id})
    unless Reservation.find_by(date: @reservation.date, period: @reservation.period)
      if @reservation.save
        redirect_to reservations_path
      else
        render :new
      end
    end
    
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end
  
  def update
    reservation = Reservation.find(params[:id])
    reservation.name = reservation_params[:name]
    reservation.date = reservation_params[:date]
    reservation.period = reservation_params[:period]
    unless Reservation.find_by(date: reservation.date, period: reservation.period)
      reservation.save
    end
    redirect_to reservations_path
  end
  
  def destroy
    reservation = Reservation.find(params[:id])
    reservation.destroy
    redirect_to reservations_path
  end
  
  private
  def reservation_params
    params.require(:reservation).permit(:user_id, :name, :date, :period, :band_id)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  skip_before_action :user_logged_in?, only: [:new, :create]
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/timetables_controller.rb
class Users::TimetablesController < ApplicationController
  def edit
    @timetables = Timetable.where(user_id: current_user.id)
  end
  
  def create
    timetable = Timetable.new(timetable_params)
    timetable.user_id = current_user.id
    timetable.save
    redirect_to edit_user_timetable_path
  end
  
  def destroy
    timetable = Timetable.find(params[:id])
    timetable.destroy
    redirect_to edit_user_timetable_path
  end
  
  private
  def timetable_params
    params.require(:timetable).permit(:day_of_week, :period)
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  def show
    @user = User.find(current_user.id)
    @timetables = Timetable.where(user_id: @user.id)
  end

  def edit
  end
end

app/helpers/users/bands_helper.rb
module Users::BandsHelper
end

app/helpers/users/reservations_helper.rb
module Users::ReservationsHelper
end

app/helpers/users/timetables_helper.rb
module Users::TimetablesHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/users/bands/edit.html.erb
<div class="container">
    <div class="row">
        <h2>バンド編集</h2>
    </div>
    <div class="row">
        <%= form_with model: @band, local: :ture do |f| %>
            <div class="form-group">
                <%= f.label "バンド名" %>
                <%= f.text_field :name, class: "form-control" %>  
            </div>
            <%= f.submit %>
        <% end %>
    </div>
    <div class="row">
        <%= link_to "削除", band_path(@band), method: :delete, class: "btn btn-danger" %>
    </div>
    
</div>

app/views/users/bands/index.html.erb
<div class="container">
    <div class="row">
        <h2>バンド一覧</h2>
    </div>
    <div class="row">
        <ul>
            <% @bands.each do |band| %>
                <li><%= link_to band.name, band_path(band) %></li>
            <% end %>
        </ul>
    </div>
    <div class="row">
        <%= link_to "バンド登録", new_band_path %>
    </div>
</div>

app/views/users/bands/new.html.erb
<div class="container">
  <div class="row">
    <h2>バンド登録</h2>
  </div>
  <div class="row">
    <%= form_with model: @band, local: :ture do |f| %>
      <div class="form-group">
        <%= f.label "バンド名" %>
        <%= f.text_field :name, class: "form-control" %>  
      </div>
      <%= f.fields_for :band_members do |g| %>
          <div class="form-group">
            <%= g.label "バンドメンバー" %>
            <%= g.collection_select :user_id, @users, :id, :name, include_blank: true %>
          </div>
      <% end %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/users/bands/show.html.erb
<div class="container">
  <div class="row">
    <h2><%= @band.name %>のメンバー</h2>
  </div>
  <div class="row">
    <ul>
      <% @band.users.each do |user| %>
        <li><%= user.name %></li>
      <% end %>
    </ul>
  </div>
  <div class="row">
    <table class="table">
      <tr>
        <th></th>
        <th>月</th>
        <th>火</th>
        <th>水</th>
        <th>木</th>
        <th>金</th>
      </tr>
      <% 5.times do |period| %>
        <tr>
          <th><%= period + 1 %></th>
          <% 5.times do |day_of_week| %>
            <td>
              <% class_count = 0 %>
              <% @band.users.each do |user| %>
                <% if user.timetables.find_by(period: period, day_of_week: day_of_week) %>
                  <% class_count += 1 %>
                <% end %>
              <% end %>
              <% if class_count > 0 %>
                ×(<%= class_count %>)
              <% else %>
                〇
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="row">
    <%= link_to "バンド編集", edit_band_path %>
    <%= link_to "バンド一覧に戻る", bands_path %>
  </div>
</div>